name: Cabal Test CI

on:
  push:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'

    # Step borrowed from Pate
    - name: Convert Submodules to Source Repos
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git config --global url."https://".insteadOf "git://"
        curl -sL https://github.com/RyanGlScott/submods-to-source-repos/releases/download/0.0.0.20211210/submods-to-source-repos-0.0.0.20211210.xz > submods-to-source-repos.xz
        echo 'f339f4bbe43af96df7e8ce115377e56f4861bab5c8f66d3129492cbe7695bbac  submods-to-source-repos.xz' | sha256sum -c -
        xz -d < submods-to-source-repos.xz > submods-to-source-repos
        rm -f submods-to-source-repos.xz
        chmod a+x submods-to-source-repos
        ./submods-to-source-repos cabal.project.dist > cabal.project
        echo "Constructed cabal.project:"
        cat cabal.project
    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    # Borrowed From Pate
    - name: Install Solvers
      run: .github/ci.sh install_system_deps
      env:
        Z3_VERSION: "4.8.8"
        YICES_VERSION: "2.6.2"
        CVC4_VERSION: "4.1.8"
    - name: Run tests
      run: cabal test all